In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.2.1


## Introduction to Tensors

In [2]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get tensor back as Python int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
MATRIX.ndim

2

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]]])

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
print(TENSOR.ndim)

3


## Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that htye start with tensors full of random numbers ant then adjust those numbers to better represent the data.

`Start with random numbers --> look at data --> update random numbers --> look at data  --> update random numbers`

https://pytorch.org/docs/stable/generated/torch.rand.html

In [15]:
# Create random tensor of size (3, 4)
random_tensor = torch.rand(3, 4, 2)
random_tensor


tensor([[[0.0930, 0.5666],
         [0.0529, 0.7962],
         [0.9817, 0.6656],
         [0.2276, 0.7006]],

        [[0.6072, 0.9878],
         [0.5518, 0.2085],
         [0.6254, 0.5563],
         [0.3750, 0.9639]],

        [[0.7858, 0.7203],
         [0.2778, 0.2310],
         [0.7152, 0.0039],
         [0.5460, 0.2592]]])

In [16]:
random_tensor.ndim

3

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(3, 224, 224)

In [18]:
random_image_size_tensor

tensor([[[5.0741e-01, 8.6139e-01, 3.5797e-01,  ..., 6.8538e-01,
          5.4911e-01, 7.8692e-01],
         [4.1312e-01, 7.6055e-01, 7.0730e-01,  ..., 7.2120e-01,
          2.8401e-01, 3.4509e-02],
         [3.4045e-01, 5.3759e-01, 3.2492e-01,  ..., 6.3261e-01,
          7.8019e-01, 3.7205e-01],
         ...,
         [8.3978e-01, 2.6813e-01, 5.5576e-01,  ..., 2.7041e-01,
          5.8181e-01, 2.8673e-01],
         [7.2445e-01, 4.4058e-01, 8.3682e-01,  ..., 6.9995e-01,
          5.5048e-01, 1.0236e-01],
         [9.8603e-01, 1.2921e-01, 7.4216e-01,  ..., 7.6820e-01,
          7.3814e-01, 8.4715e-01]],

        [[9.4325e-01, 7.5505e-02, 3.3845e-01,  ..., 4.5255e-02,
          8.7225e-01, 6.5809e-01],
         [9.9969e-01, 5.7836e-01, 7.3076e-01,  ..., 4.3435e-01,
          2.0796e-01, 1.3326e-01],
         [5.0686e-01, 3.3520e-01, 8.0507e-01,  ..., 1.8396e-01,
          6.1151e-01, 5.1464e-01],
         ...,
         [3.3211e-01, 8.5078e-01, 1.6719e-01,  ..., 8.5497e-01,
          4.741

### Zeros and Ones

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype, zeros.dtype, random_tensor.dtype

(torch.float32, torch.float32, torch.float32)

## Create a range of tensors and tensor like

In [22]:
#torch.range(0, 10)
one_to_ten = torch.arange(start=1, end=11, step=1)   # 1 to 10
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch && Deep Learning:
1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

In [24]:
float_32_tensor = torch.tensor([3.0, 4.0, 6.0],
                               dtype=None,  # what datatypeis the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on (e.g 'cpu', 'cuda')
                               requires_grad=False) # whether or not to track gradient with this tensor operations
float_32_tensor

tensor([3., 4., 6.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 6.], dtype=torch.float16)

In [27]:
float_16_tensor * float_32_tensor

tensor([ 9., 16., 36.])

In [28]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

## Getting information from tensors (tensor attributes)

1. Get datatype --> tensor.dtype

2. Get shape --> tensor.shape

3. Get device --> tensor.device

In [29]:
some_tensor = torch.rand(3, 4)
print(f'Datatype: {some_tensor.dtype}')
print(f'Shape: {some_tensor.shape}')
print(f'Device: {some_tensor.device}')

Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating tensor

Tensor operations includes;

1. Addition
2. Substraction
3. Element-wise multiplication
4. Division
5. Matrix multiplication

In [30]:
# Create tensor add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [31]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

There are another built in PyTorch functions such as add or mul but using default Python functions

### Matrix multiplication

Two main ways of performing multiplication in neural networks and depp learning:

1. Element-wise multiplication
2. Matrix multiplication

In [32]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [33]:
# Matrix multiplication
torch.matmul(tensor, tensor)


tensor(14)

**Some notes on matrix multiplications**

1. @ symbol does same operation
2. Inner dimensions must match
3. Vectors are exceptions if their size is same. Pytorch understand it

In [34]:
tensor_A = torch.rand(3, 2)
tensor_B = torch.rand(3, 2)
# torch.matmul(tensor_A, tensor_B)   ----->   FAIL
torch.matmul(tensor_A.T, tensor_B)

tensor([[0.9746, 1.3909],
        [0.7031, 0.9284]])

### Min, Max, Sum, Mean

In [35]:
x = torch.arange(start=0, end=100, step=10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
# Min - Max
x.min(), torch.min(x), x.max(), torch.max(x)

(tensor(0), tensor(0), tensor(90), tensor(90))

In [37]:
# Mean - note: torch.mean() function requires a tensor of float32
x.type(torch.float32).mean()


tensor(45.)

In [38]:
# Sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

### Finding the positional min and max

In [39]:
# Find the position in tensor that has the minimum value with argmin()
# returns index position of target tensor where the minimum value occurs
x = torch.arange(1, 101, 10)
print(x)
x.argmin()

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])


tensor(0)

In [40]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()


tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input trensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [41]:
# Let's create a tensor
import torch
x = torch.arange(1., 10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [42]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [43]:
# Change the view
z = x.view(1, 9)
z, z.shape
# Very similar to rehshape, only difference viewed var. shares same memory with original one

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [44]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [45]:
# Stack tensor top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

#### Squeeze

In [46]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [47]:
# Squeeze - removes `1`dimensions`
x = torch.zeros(2, 1, 2, 1, 2)
x.size()


torch.Size([2, 1, 2, 1, 2])

In [48]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [49]:
x_reshaped.squeeze() 
# Removes single dimension

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [50]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0) # Add dimension to 0th dimension
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [51]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # Shify axis 0 -> 1, 1-> 2, 0 -> 1

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Indexing with Pytorch is similar with Numpy

In [52]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [53]:
print(x[0])   # Index on outer bracket (dim=0)
print(x[0][0]) # Index on middle bracket (dim=1)
print(x[0][0][0]) # Index on inner bracket (dim=2)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [54]:
print(x[:, :, 1])

tensor([[2, 5, 8]])


In [55]:
# Index on x to return 9
print(x[0][2][2])
# index on x to return 3
print(x[0][0][2])

tensor(9)
tensor(3)


## PyTorch tensors & NumPy

Numpy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor `torch.from_numpy(ndarray)`;
* Pytorch tensor --> NumPy:    `torch.Tensor.numpy()`

In [56]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1., 10.)
tensor = torch.from_numpy(array) # warning: when converting from numpy --> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [57]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again - again ...

To reduce the randomness in neural newworks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness

https://pytorch.org/docs/stable/notes/randomness.html

In [60]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A == random_tensor_B)
# Of course all elements gives False

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [61]:
# Let's make some random but reproducible tensors

# Set random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) # It states a seed. Then, next lines follows that seed. Therefore, random_tensor_C and random_tensor_D will not be same

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C == random_tensor_D)
# It gives False for all elements

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [62]:
# Let's set random seed for both tensor seperately

torch.manual_seed(RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED) # Reset seed. Therefore random_tensor_D and random_tensor_C will be same
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C == random_tensor_D)
# It gives True for all elements

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPU's (and making faster computations) 
GPU's = faster computations on numbersi thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options.
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

For setup:

cuda: https://pytorch.org/docs/stable/notes/cuda.html

mps: https://pytorch.org/docs/stable/notes/mps.html

In [79]:
### 2. Check for GPU access with PyTorch
import torch

# Checking for cuda GPU's (for colab)
print(torch.cuda.is_available())

# Checking for Apple GPU's (for my Mac)
print(torch.backends.mps.is_available())

False
True


In [80]:
# Setup device agnostic code

# For cuda
device = "cuda" if torch.cuda.is_available() else "cpu"

# For Mac
device = "mps" if torch.backends.mps.is_available() else "cpu"

In [77]:
# Count number of devices

# For cuda
print(torch.cuda.device_count())

0


### Putting tensors on the GPU

The reason we want our tensor/models on the GPU is because using GPU results in faster computations.

In [82]:
# Create a tensor(default on CPU)
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [84]:
# Move tensor to GPU (if available)
device = "mps" if torch.backends.mps.is_available() else "cpu"
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='mps:0'), device(type='mps', index=0))

### Moving tensors back to CPU

In [89]:
# If a tensor is on the GPU, can't transform it to NumPy
tensor_on_gpu.numpy() 

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [94]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
array = tensor_back_on_cpu.numpy()
array



array([1, 2, 3])