In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

## Introduction to Tensors

In [4]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [6]:
scaler.ndim

0

In [7]:
# Get tensor back as Python int
scaler.item()

7

In [9]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([2])

In [38]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [39]:
MATRIX.shape

torch.Size([2, 2])

In [40]:
MATRIX.ndim

2

In [41]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]]])

In [42]:
TENSOR.shape

torch.Size([1, 3, 3])

In [43]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [44]:
print(TENSOR.ndim)

3


## Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that htye start with tensors full of random numbers ant then adjust those numbers to better represent the data.

`Start with random numbers --> look at data --> update random numbers --> look at data  --> update random numbers`

https://pytorch.org/docs/stable/generated/torch.rand.html

In [52]:
# Create random tensor of size (3, 4)
random_tensor = torch.rand(3, 4, 2)
random_tensor


tensor([[[0.0831, 0.4189],
         [0.4633, 0.8707],
         [0.3834, 0.0665],
         [0.1829, 0.7072]],

        [[0.1107, 0.9981],
         [0.8175, 0.4867],
         [0.9992, 0.3918],
         [0.9635, 0.3373]],

        [[0.6411, 0.5209],
         [0.0857, 0.9540],
         [0.9801, 0.8899],
         [0.2527, 0.2151]]])

In [51]:
random_tensor.ndim

3

In [55]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(3, 224, 224)

In [56]:
random_image_size_tensor

tensor([[[0.1052, 0.9582, 0.3396,  ..., 0.7037, 0.4112, 0.6311],
         [0.8361, 0.1431, 0.0224,  ..., 0.4256, 0.6208, 0.1102],
         [0.6731, 0.6704, 0.4897,  ..., 0.4295, 0.8997, 0.9000],
         ...,
         [0.4506, 0.9660, 0.7891,  ..., 0.7775, 0.1730, 0.2828],
         [0.0043, 0.4230, 0.9819,  ..., 0.1286, 0.3013, 0.9461],
         [0.8806, 0.0270, 0.7936,  ..., 0.8602, 0.6035, 0.1725]],

        [[0.8327, 0.4063, 0.9392,  ..., 0.1798, 0.6541, 0.1626],
         [0.9737, 0.3049, 0.0596,  ..., 0.0891, 0.1880, 0.4172],
         [0.4615, 0.6120, 0.2069,  ..., 0.4413, 0.0536, 0.6728],
         ...,
         [0.7492, 0.4577, 0.1991,  ..., 0.2213, 0.9594, 0.1082],
         [0.9860, 0.0750, 0.0485,  ..., 0.8324, 0.9082, 0.0031],
         [0.1933, 0.4642, 0.8423,  ..., 0.0990, 0.8944, 0.0536]],

        [[0.3747, 0.4319, 0.9831,  ..., 0.3835, 0.0300, 0.9599],
         [0.1218, 0.0891, 0.6002,  ..., 0.6627, 0.9639, 0.8419],
         [0.5756, 0.7273, 0.2798,  ..., 0.8088, 0.4910, 0.

### Zeros and Ones

In [59]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [61]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [65]:
ones.dtype, zeros.dtype, random_tensor.dtype

(torch.float32, torch.float32, torch.float32)

## Create a range of tensors and tensor like

In [77]:
#torch.range(0, 10)
one_to_ten = torch.arange(start=1, end=11, step=1)   # 1 to 10
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
# Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch && Deep Learning:
1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 4.0, 6.0],
                               dtype=None,  # what datatypeis the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on (e.g 'cpu', 'cuda')
                               requires_grad=False) # whether or not to track gradient with this tensor operations
float_32_tensor

In [87]:
float_32_tensor.dtype

torch.float32

In [91]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 6.], dtype=torch.float16)

In [92]:
float_16_tensor * float_32_tensor

tensor([ 9., 16., 36.])

In [94]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

## Getting information from tensors (tensor attributes)

1. Get datatype --> tensor.dtype

2. Get shape --> tensor.shape

3. Get device --> tensor.device

In [95]:
some_tensor = torch.rand(3, 4)
print(f'Datatype: {some_tensor.dtype}')
print(f'Shape: {some_tensor.shape}')
print(f'Device: {some_tensor.device}')

Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu
