# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[3.6611e-01, 2.7510e-01, 1.5902e-01, 3.7755e-03, 8.5513e-01, 1.6895e-01,
         2.2515e-01],
        [8.4220e-02, 2.9147e-02, 9.1898e-01, 4.5584e-01, 8.1294e-01, 1.6650e-02,
         4.5776e-01],
        [4.2702e-01, 8.0042e-01, 1.5771e-01, 2.4191e-02, 5.5326e-01, 3.6899e-01,
         3.9939e-01],
        [1.5433e-01, 9.0554e-01, 4.2084e-01, 4.4816e-02, 6.3730e-01, 4.9817e-01,
         2.0994e-01],
        [8.8299e-01, 7.3069e-04, 6.2888e-02, 8.5190e-01, 6.1583e-01, 2.5621e-01,
         1.0570e-01],
        [2.8140e-01, 4.4458e-01, 9.9624e-01, 8.1290e-01, 6.6835e-01, 8.7030e-01,
         2.6854e-02],
        [5.6666e-01, 6.1407e-01, 3.3676e-01, 6.7550e-01, 7.9295e-01, 1.7663e-01,
         8.2914e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
random_tensor2 = torch.rand(1, 7)
# Perform matrix multiplication 
random_tensor.matmul(random_tensor2.T)

tensor([[1.1539],
        [1.0063],
        [1.1693],
        [1.1150],
        [1.7944],
        [1.8740],
        [1.6125]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [20]:
# Set manual seed
RANDOM_SEED = 0
# Create two random tensors
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(7, 7)
random_tensor2 = torch.rand(1, 7)
# Matrix multiply tensors
print(random_tensor)
print(random_tensor2)
random_tensor.matmul(random_tensor2.T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [26]:
# Set random seed on the GPU
torch.mps.manual_seed(2000)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [28]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.backends.mps.is_available()
device = "mps" if torch.backends.mps.is_available() else "cpu"

# Create two random tensors on GPU
tensor1 = torch.rand(2, 3).to(device=device)
tensor2 = torch.rand(2, 3).to(device=device)
tensor1, tensor2


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [30]:
# Perform matmul on tensor_A and tensor_B
final_tensor = torch.matmul(tensor1, tensor2.T)
final_tensor

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='mps:0')

### 8. Find the maximum and minimum values of the output of 7.

In [32]:
# Find max
final_tensor.max()
# Find min
final_tensor.min()



tensor(0.3647, device='mps:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [34]:
# Find arg max
final_tensor.argmax()
# Find arg min
final_tensor.argmin()

tensor(0, device='mps:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [36]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor7 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed_tensor = random_tensor7.squeeze()

# Print out tensors and their shapes
squeezed_tensor, squeezed_tensor.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))